"""Add nullable org_id column

Revision ID: 7a159de1064c
Revises: 1b82aeb7431f
Create Date: 2025-04-11 12:32:20.415772+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a159de1064c'
down_revision: Union[str, None] = '1b82aeb7431f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('org_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'org_id')
    # ### end Alembic commands ###
