"""added custom instructions to agent table

Revision ID: adcfaa729f61
Revises: c6f47d7d2fa1
Create Date: 2025-01-27 16:57:57.358842+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adcfaa729f61"
down_revision: Union[str, None] = "c6f47d7d2fa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("custom_instructions", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "custom_instructions")
    # ### end Alembic commands ###
