"""Make org_id of project table not nullable

Revision ID: a79cdd14460e
Revises: 7a159de1064c
Create Date: 2025-04-11 12:36:10.907555+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79cdd14460e'
down_revision: Union[str, None] = '7a159de1064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
