"""add last_used_at to linked_accounts

Revision ID: ce439f017e25
Revises: 7ecafab6f8f9
Create Date: 2025-04-29 12:20:50.965618+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce439f017e25'
down_revision: Union[str, None] = '7ecafab6f8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linked_accounts', 'last_used_at')
    # ### end Alembic commands ###
